id: 67d0a5b5caa641ff94f1d92e842302f2
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_150-The_Inquiry_of_Avalokitesvara_on_the_Seven_Qualities-v1
  language: en
  author: ''
  volume: {}
